name: lhie1-Rules-sync
on:
  schedule:
    - cron: '32 */3 * 1 *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-lhie1-Rules-tree-master
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync lhie1-Rules-tree-master
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lhie1/Rules.git"
          source_branch: "master"
          destination_branch: "lhie1-Rules"
          github_token: ${{ secrets.PAT }}
